version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./meetting_room_booking_system_backend  # 后端项目路径
      dockerfile: Dockerfile                            # 后端 Dockerfile
    ports:
      - "3333:3333"  # 宿主机端口:容器端口
    environment:
      # 后端环境变量（直接从 .env 读取，确保后端 .env 已创建）
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=woaini520.
      - DB_DATABASE=apparel_admin_db

      - PORT=3333
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
      
      # 七牛云配置 - 请填入您的实际配置
      - QINIU_ACCESS_KEY=eDtP3sBtDPSfRAC_hLJjIFDURLuxsnuafUo4JTH7
      - QINIU_SECRET_KEY=RrTc2FiMj3Q9Wh4r4xSnPqXVrrfrLzu47786D3-C
      - QINIU_BUCKET_NAME=xin-zone
      - QINIU_DOMAIN=http://img.fznbd.xin

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  # 前端服务
  frontend:
    build:
      context: ./vue3-admin-dashboard  # 前端项目路径
      dockerfile: Dockerfile            # 前端 Dockerfile
    ports:
      - "5173:80"  # 宿主机5173端口映射到容器80端口
    depends_on:
      - backend
    networks:
      - app-network

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=woaini520.  # 使用默认密码
      - MYSQL_DATABASE=apparel_admin_db  # 数据库名
    volumes:
      - mysql-data:/var/lib/mysql  # 数据持久化
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10



# 网络配置
networks:
  app-network:
    driver: bridge

# 数据卷（持久化数据）
volumes:
  mysql-data: